# Generated by Django 5.1 on 2026-04-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_avatar_url_room_cover_image_room_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_live',
        ),
        migrations.RemoveField(
            model_name='room',
            name='participant_count',
        ),
    ]
