"""
Django settings for auth project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
ALLOWED_HOSTS = ['*']  if DEBUG else ALLOWED_HOSTS  # allow all in debug, restrict in production
# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'channels',
    'api',
    'events',
    'delegation',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'auth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'auth.wsgi.application'
ASGI_APPLICATION = 'auth.asgi.application'

# Channel layers — in-memory for dev, Redis for production
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(os.getenv('REDIS_HOST', 'redis'), int(os.getenv('REDIS_PORT', 6379)))],
        },
    } if os.getenv('REDIS_HOST') else {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
}

# Cache (used by DRF throttling). Use Redis when available for shared limits.
if os.getenv('REDIS_HOST'):
    _redis_host = os.getenv('REDIS_HOST', 'redis')
    _redis_port = int(os.getenv('REDIS_PORT', 6379))
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': f"redis://{_redis_host}:{_redis_port}/1",
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'music-room',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'music-room-locmem',
        }
    }


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DJANGO_DATABASE_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.getenv("POSTGRES_DB", "postgres"),
        "USER": os.getenv("POSTGRES_USER", "postgres"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST", "auth-postgres"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
        "CONN_MAX_AGE": 60,  # persistent connections — avoids reconnect on every request
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        # Rejects passwords too similar to the user's email/username
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Hard minimum — 8 chars (serializer enforces more on top of this)
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        # Rejects passwords from the list of 20k most common passwords
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # Rejects fully numeric passwords (e.g. "12345678")
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#from here

AUTH_USER_MODEL = 'api.CustomUser'


REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Rate limiting — protects login, register, forgot-password from brute force

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/min',   
        'user': '150/min',
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}


import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


from datetime import timedelta


with open(os.path.join(BASE_DIR, 'keys/private.key'), 'r') as f:
    PRIVATE_KEY = f.read()

with open(os.path.join(BASE_DIR, 'keys/public.key'), 'r') as f:
    PUBLIC_KEY = f.read()

SIMPLE_JWT = {
    "ALGORITHM": "RS256",
    "SIGNING_KEY": PRIVATE_KEY,
    "VERIFYING_KEY": PUBLIC_KEY,
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "sub",
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    "ISSUER": "auth-backend",
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}



# reset password email sender

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'          # or your provider’s SMTP
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")   # the sender email
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")        # use an App Password (not your Gmail password)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# CORS — restrict to explicit origins (never use CORS_ALLOW_ALL_ORIGINS=True in production)
# Default allows both 8080 (nginx-served Flutter web) and 8081 (local dev)
CORS_ALLOW_ALL_ORIGINS = True
_cors_defaults = 'http://localhost:8080,http://localhost:8081,http://localhost:9090'
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', _cors_defaults).split(',')
CORS_ALLOW_CREDENTIALS = True



GOOGLE_CLIENT_ID = (
    os.getenv("GOOGLE_OAUTH_CLIENT_ID")
    or os.getenv("GOOGLE_CLIENT_ID")
    or ""
)
_allowed_ids = os.getenv("GOOGLE_OAUTH_CLIENT_IDS", "")
GOOGLE_ALLOWED_CLIENT_IDS = [id.strip() for id in _allowed_ids.split(",") if id.strip()]
if GOOGLE_CLIENT_ID and GOOGLE_CLIENT_ID not in GOOGLE_ALLOWED_CLIENT_IDS:
    GOOGLE_ALLOWED_CLIENT_IDS.append(GOOGLE_CLIENT_ID)
GOOGLE_CLIENT_SECRET = (
    os.getenv("GOOGLE_OAUTH_CLIENT_SECRET")
    or os.getenv("GOOGLE_CLIENT_SECRET")
    or ""
)
FACEBOOK_CLIENT_ID = (
    os.getenv("FACEBOOK_OAUTH_CLIENT_ID")
    or os.getenv("FACEBOOK_CLIENT_ID")
    or ""
)
FACEBOOK_CLIENT_SECRET = (
    os.getenv("FACEBOOK_OAUTH_CLIENT_SECRET")
    or os.getenv("FACEBOOK_CLIENT_SECRET")
    or ""
)



SPECTACULAR_SETTINGS = {
    'TITLE': 'App Auth API',
    'DESCRIPTION': (
        'Authentication & user management service for App.\n\n'
        '## Authentication\n'
        'This API uses **JWT Bearer tokens**.\n'
        '1. Call `POST /api/token/` with your email & password to get `access` and `refresh` tokens.\n'
        '2. Add `Authorization: Bearer <access_token>` header to protected endpoints.\n'
        '3. When the access token expires, call `POST /api/token/refresh/` with your `refresh` token.\n'
        '4. To log out, call `POST /api/logout/` with your `refresh` token (it gets blacklisted).\n\n'
        '## Token Info\n'
        '- Access token lifetime: **1 day**\n'
        '- Refresh token lifetime: **30 days**\n'
        '- Algorithm: **RS256**\n'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'CONTACT': {'name': 'App Dev Team'},

    # Group endpoints by tags instead of app name
    'TAGS': [
        {'name': 'Auth', 'description': 'Login, logout, token refresh'},
        {'name': 'Register', 'description': 'User registration'},
        {'name': 'Profile', 'description': 'Get and update the authenticated user profile'},
        {'name': 'Password', 'description': 'Change, forgot and reset password'},
        {'name': 'OAuth', 'description': 'Social login (Google / Facebook)'},
        {'name': 'Events – Track Vote', 'description': 'Suggest tracks and vote in vote-type rooms'},
        {'name': 'Delegation', 'description': 'Device control delegation in delegation-type rooms'},
    ],

    # Security scheme — tells Swagger UI to send Bearer tokens
    'SECURITY': [{'BearerAuth': []}],
    'SECURITY_DEFINITIONS': {
        'BearerAuth': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
        }
    },

    # Cleaner output
    'SORT_OPERATIONS': False,
    'ENUM_GENERATE_CHOICE_DESCRIPTION': False,
    'COMPONENT_SPLIT_REQUEST': True,      # separate request/response schemas
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.hooks.postprocess_schema_enums',
    ],
}
