# Generated by Django 5.1 on 2026-04-14 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_passwordresetcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Track title', max_length=255)),
                ('artist', models.CharField(help_text='Artist / band name', max_length=255)),
                ('external_url', models.URLField(blank=True, help_text='Optional link to Spotify, YouTube, etc.')),
                ('vote_count', models.IntegerField(default=0, help_text='Total number of votes — updated atomically.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(help_text='The vote-type room this track belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.room')),
                ('suggested_by', models.ForeignKey(help_text='The user who suggested this track.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-vote_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(help_text='Denormalised FK for fast per-room queries.', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.room')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='events.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('track', 'user')},
            },
        ),
    ]
