# Generated by Django 5.1 on 2026-04-15 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-vote_count', '-created_at', '-id']},
        ),
    ]
