# Generated by Django 5.1 on 2026-04-16 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_track_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='external_url',
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.CharField(blank=True, help_text='Album name', max_length=255),
        ),
        migrations.AddField(
            model_name='track',
            name='album_art',
            field=models.URLField(blank=True, help_text='URL to album cover', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Spotify 30s preview_url', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='track',
            name='suggested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='track',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
