# Generated by Django 5.1 on 2026-04-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_track_album_art_alter_track_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_played',
            field=models.BooleanField(default=False),
        ),
    ]
