# Generated by Django 5.1 on 2026-04-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_track_is_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Deezer 30s  preview_url', max_length=2000, null=True),
        ),
    ]
