# Generated by Django 5.1 on 2026-04-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_avatar_url_room_cover_image_room_genres_and_more'),
        ('events', '0003_remove_track_external_url_track_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(default='', help_text='Unique Spotify Track ID (e.g. 4iV5W9uYEdYUVa79Axb7Rh)', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('room', 'spotify_id')},
        ),
    ]
