# Generated by Django 5.1 on 2026-04-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_spotify_id_to_deezer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album_art',
            field=models.URLField(blank=True, help_text='URL to album cover', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Deezer 30s preview_url', max_length=2000, null=True),
        ),
    ]
