# Generated by Django 5.1 on 2026-04-14 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_passwordresetcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_identifier', models.CharField(help_text='Unique device ID (e.g. UUID from the mobile app).', max_length=255)),
                ('device_name', models.CharField(help_text='Human-readable device name (e.g. "Living Room Speaker").', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delegated_to', models.ForeignKey(blank=True, help_text='The friend who currently has control (null = owner controls).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_controls', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='The user who owns this device.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_delegations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(help_text='The delegation-type room.', on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='api.room')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('room', 'device_identifier')},
            },
        ),
    ]
