services:
  auth-postgres:
    image: postgres:15
    restart: unless-stopped
    networks:
      - transcendence
    ports:
      - "5433:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    env_file: .env

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - transcendence
    ports:
      - "6379:6379"

  auth-service:
    depends_on:
      - auth-postgres
      - redis
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - transcendence
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  transcendence:
    driver: bridge

volumes:
  auth_pgdata:
