# Generated by Django 5.1 on 2026-04-15 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.CharField(help_text='Client-provided idempotency key (e.g. UUID). Unique per device.', max_length=64)),
                ('action_type', models.CharField(choices=[('play', 'Play'), ('pause', 'Pause'), ('skip', 'Skip Next'), ('previous', 'Previous')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='delegation.devicedelegation')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('device', 'action_id')},
            },
        ),
    ]
