# Generated by Django 5.1 on 2026-04-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('vote', 'Music Track Vote'), ('delegation', 'Music Control Delegation')], max_length=20),
        ),
    ]
