# Generated by Django 5.1 on 2026-04-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, default='https://i.pravatar.cc/100', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='cover_image',
            field=models.URLField(blank=True, help_text="URL for the room's cover art", null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='genres',
            field=models.JSONField(blank=True, default=list, help_text='List of genres e.g., ["Pop", "EDM"]'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Is the room currently active/live?'),
        ),
        migrations.AddField(
            model_name='room',
            name='participant_count',
            field=models.IntegerField(default=0, help_text='Number of listeners currently in the room'),
        ),
    ]
