# Generated by Django 5.1 on 2026-04-22 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_room_is_live_remove_room_participant_count'),
        ('events', '0006_alter_track_album_art_alter_track_audio_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPlaybackState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('playing', 'Playing'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='stopped', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('position_ms', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.track')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playback_state', to='api.room')),
            ],
        ),
    ]
