# Generated by Django 5.1 on 2026-04-14 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_passwordresetcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Track title', max_length=255)),
                ('artist', models.CharField(help_text='Artist / band name', max_length=255)),
                ('external_url', models.URLField(blank=True, help_text='Optional link to Spotify, YouTube, etc.')),
                ('position', models.PositiveIntegerField(help_text='Playback order (0-based). Lower = earlier.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(help_text='The user who added this track.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist_tracks_added', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(help_text='The playlist-type room this track belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tracks', to='api.room')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('room', 'position')},
            },
        ),
    ]
