# Generated by Django 5.1 on 2026-04-15 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_passwordresetcode'),
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistVersion',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='playlist_version', serialize=False, to='api.room')),
                ('version', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
