# Generated by Django 5.1 on 2026-04-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlisttrack',
            name='audio_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
